version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  app:
    depends_on:
      - 'postgres'
    build: .
    command: bash -c "bundle exec puma -C config/puma.rb"
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/app/'
      - 'gem_cache:/gems'

volumes:
  postgres:
  gem_cache:
